[32mINFO    [0m root:test_calculator.py:80 除法P2开始运行测试
[32mINFO    [0m root:test_calculator.py:81 数据[-3, 'None', 'TypeError']
[32mINFO    [0m root:test_calculator.py:83 异常<ExceptionInfo for raises contextmanager>