[32mINFO    [0m root:test_calculator.py:35 加法P1_1开始运行测试
[32mINFO    [0m root:test_calculator.py:36 数据[1, -99.01, '参数大小超出范围']